apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lyh-ns
type: Opaque
stringData:
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: change-me
  MYSQL_ROOT_PASSWORD: change-me-root
