clusterDomain: cluster.local

nginxGateway:
  gatewayClassName: nginx
  replicas: 2
  imagePullSecret: "{image_pull_secret_name}"
  imagePullSecrets:
    - "{image_pull_secret_name}"
  image:
    repository: "{private_registry}/{nginx_gateway_repository}"
    tag: "{nginx_gateway_image_tag}"
    pullPolicy: IfNotPresent
  service:
    annotations: {}

nginx:
  kind: deployment
  replicas: 2
  image:
    repository: "{private_registry}/{nginx_data_plane_repository}"
    tag: "{nginx_data_plane_image_tag}"
    pullPolicy: IfNotPresent
  imagePullSecret: "{image_pull_secret_name}"
  imagePullSecrets:
    - "{image_pull_secret_name}"
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
