global:
  image:
    registry: "{private_registry}"
  imagePullSecrets:
    - name: "{image_pull_secret_name}"
  # 사설 인증서가 필요한 경우 아래 주석을 해제하고 인증서를 입력합니다.
  # caCertificates:
  #   data: |
  #     -----BEGIN CERTIFICATE-----
  #     ...
  #     -----END CERTIFICATE-----

image:
  repository: kyverno/kyverno-cli
  tag: v1.17.1

admissionController:
  replicas: 2
  container:
    image:
      repository: kyverno/kyverno
      tag: v1.17.1
  initContainer:
    image:
      repository: kyverno/kyvernopre
      tag: v1.17.1

backgroundController:
  replicas: 1
  image:
    repository: kyverno/background-controller
    tag: v1.17.1

cleanupController:
  replicas: 1
  image:
    repository: kyverno/cleanup-controller
    tag: v1.17.1

reportsController:
  replicas: 1
  image:
    repository: kyverno/reports-controller
    tag: v1.17.1

test:
  image:
    repository: kyverno/readiness-checker
    tag: v0.1.0
  imagePullSecrets:
    - name: "{image_pull_secret_name}"

webhooksCleanup:
  enabled: false
