apiVersion: v1
kind: Pod
metadata:
  name: kyverno-test-pod-no-pullsecret
  namespace: "{target_namespace}"
  labels:
    app: kyverno-test-pod-no-pullsecret
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: "{source_registry}/{image_repository}:{image_tag}"
      command:
        - /bin/sh
        - -c
        - sleep 3600
