apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-test-deployment-empty-pullsecret
  namespace: "{target_namespace}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyverno-test-deployment-empty-pullsecret
  template:
    metadata:
      labels:
        app: kyverno-test-deployment-empty-pullsecret
    spec:
      imagePullSecrets: []
      containers:
        - name: test
          image: "{source_registry}/{image_repository}:{image_tag}"
          command:
            - /http-echo
          args:
            - "-text={test_response_text}"
