apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kyverno-test-statefulset-existing-pullsecret
  namespace: "{target_namespace}"
spec:
  serviceName: kyverno-test-statefulset-existing-pullsecret
  replicas: 1
  selector:
    matchLabels:
      app: kyverno-test-statefulset-existing-pullsecret
  template:
    metadata:
      labels:
        app: kyverno-test-statefulset-existing-pullsecret
    spec:
      imagePullSecrets:
        - name: "{existing_image_pull_secret_name}"
      containers:
        - name: test
          image: "{source_registry}/{image_repository}:{image_tag}"
          command:
            - /bin/sh
            - -c
            - sleep 3600
