image:
  repository: "{private_registry}/{velero_server_repository}"
  tag: "{velero_server_image_tag}"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - "{image_pull_secret_name}"

kubectl:
  image:
    repository: "{private_registry}/{kubectl_repository}"
    tag: "{kubectl_image_tag}"

upgradeCRDs: true
cleanUpCRDs: false

deployNodeAgent: true
snapshotsEnabled: false
backupsEnabled: true

defaultVolumesToFsBackup: true

initContainers:
  - name: velero-plugin-for-aws
    image: "{private_registry}/{velero_plugin_repository}:{velero_plugin_image_tag}"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  name: velero-credentials
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=CHANGE_ME_ACCESS_KEY
      aws_secret_access_key=CHANGE_ME_SECRET_KEY

configuration:
  uploaderType: restic
  defaultBackupStorageLocation: default
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: ta-lyh-obs
      default: true
      accessMode: ReadWrite
      credential:
        name: velero-credentials
        key: cloud
      config:
        region: kr2
        s3ForcePathStyle: "true"
        s3Url: https://kr2-api-object-storage.nhncloudservice.com
        checksumAlgorithm: ""
  volumeSnapshotLocation: []
